server:
  port: 8080
  servlet:
    context-path: /fy_web

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 800
      min-idle: 50
      initial-size: 200




mybatis:
  mapper-locations: classpath:com/fy/mapper/*.xml
  config-location: classpath:/mybatis-config.xml